config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    root to: "devise/sessions#new"

  end

  get 'admin/homepage', as: :admin_root
  get 'admin/start' => 'admin#start'
  get 'admin/end' => 'admin#end'
  get 'admin/delete' => 'admin#delete'
  get 'admin/new' => 'admin#new'
  get 'admin/edit' => 'admin#edit'
  get 'admin/invite' => 'admin#invite'
  get 'admin/delete_invitee' => 'admin#delete_invitee'
  post 'admin/add_invitee' => 'admin#add_invitee'
  post 'admin/send_invites' => 'admin#send_invites'
  get 'admin/log_out' => 'admin#log_out'

  get 'poll/new' => 'poll#new'
  get 'poll/edit' => 'poll#edit'
  post 'poll/edit_time_slots' => 'poll#edit_time_slots'
  post 'poll/update' => 'poll#update'
  post 'poll/choose_time_slots' => 'poll#choose_time_slots'
  post 'poll/create' => 'poll#create'
  get 'poll/vote' => "poll#vote"
  post 'poll/cast_vote' => "poll#cast_vote"
  get 'poll/success' => "poll#success"
  get 'poll/unauthorized' => "poll#unauthorized"

  get 'results/get_results' => 'results#get_results'

end

app/views/admin/homepage.html.erb
<head>
  <div class="menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="homepage">Current Polls</a>
      </div>
      <div>
        <ul class="nav navbar-nav navbar-right">
          <li><a>Logged in as: <%= @current_user %></a></li>

          <li> <%= link_to 'Log Out', destroy_admin_session_path, method: :delete %> </li>
<!--          <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Log Out </a></li>-->
        </ul>
      </div>
    </div>
  </div>
</head>



<body>

  <table id="poll_table" style="width:1100px;margin:0 auto;font-size:20px;position:relative;top:65px" class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">Poll Name</th>
        <th scope="col">Status</th>
        <th scope="col">Deadline</th>
        <th scope="col"></th>
        <th scope="col" ></th>
      </tr>
    </thead>

    <tbody>

      <% @not_started_polls.each do |poll| %>
        <tr class="warning">
          <td><%= poll.poll_name %></td>
          <td><%=poll.status%> <%= link_to 'Start', "start?start_poll="+poll.id.to_s , {class: 'btn btn-success btn-xs', type: 'button'} %></td>
          <% if not poll.deadline.eql? nil %>
            <td><%=poll.deadline%></td>
          <% else %>
            <td>-</td>
          <% end %>
          <td align="right"><%= link_to "Edit <span class='glyphicon glyphicon-pencil'></span>".html_safe, "edit?edit_poll="+poll.id.to_s , {class: 'btn btn-default', type: 'button'} %></td>
          <td><%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, "delete?delete_poll="+poll.id.to_s , {class: 'btn btn-danger', type: 'button'} %></td>
        </tr>
      <% end %>

      <% @active_polls.each do |poll| %>
      <tr class="success">
        <td><%= poll.poll_name %></td>
        <td><%=poll.status%> <%= link_to 'Invite', "invite?poll_invite="+poll.id.to_s , {class: 'btn btn-info btn-xs', type: 'button'} %> <%= link_to 'End', "end?end_poll="+poll.id.to_s , {class: 'btn btn-warning btn-xs', type: 'button'} %></td>
        <% if not poll.deadline.eql? nil%>
          <td><%=poll.deadline%></td>
        <% else %>
          <td>-</td>
        <% end %>
<!--        <td align="right"><button type="button" class="btn btn-primary">View Live Results</button></td>-->
        <td align="right"><%= link_to "View Live Results", results_get_results_url(:poll_id => poll.id) , {class: 'btn btn-primary', type: 'button'} %></td>
        <td><%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, "delete?delete_poll="+poll.id.to_s , {class: 'btn btn-danger', type: 'button'} %></td>
      </tr>
    <% end %>

    <% @finished_polls.each do |poll| %>
      <tr class="active">
        <td><%= poll.poll_name %></td>
        <td><%=poll.status%></td>
        <% if not poll.deadline.eql? nil%>
          <td><%=poll.deadline%></td>
        <% else %>
          <td>-</td>
        <% end %>
<!--        <td align="right"><button type="button" class="btn btn-primary">View Final Results</button></td>-->
        <td align="right"><%= link_to "View Final Results", results_get_results_url(:poll_id => poll.id) , {class: 'btn btn-primary', type: 'button'} %></td>
        <td><%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, "delete?delete_poll="+poll.id.to_s , {class: 'btn btn-danger', type: 'button'} %></td>
      </tr>
    <% end %>

        </tbody>

  </table>

  <%=  button_to 'Create New Poll', "new" , {class: 'btn btn-secondary create_new_button', type: 'button', method: 'get'} %>

</body>

app/views/admin/invite.html.erb
<head>
  <div class="menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="homepage">Current Polls</a>
      </div>
      <div>
        <ul class="nav navbar-nav navbar-right">
          <li><a>Logged in as: <%= @current_user %></a></li>

          <li> <%= link_to 'Log Out', destroy_admin_session_path, method: :delete %> </li>
          <!--          <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Log Out </a></li>-->
        </ul>
      </div>
    </div>
  </div>
</head>


<body>

<h1 class="invite_header"> <%= @poll.poll_name %>'s Invitees</h1>

<%= content_tag :div, id: 'datadiv', class: "poll_id", data: {poll_id: @poll.id.to_s} do %>
<% end %>

<table id="poll_table" style="width:500px;margin:0 auto;font-size:20px;position:relative;top:-40px" class="table table-striped table-sm">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col" >Phone Number</th>
  </tr>
  </thead>

  <tbody>

    <% @invitees.each do |invitee| %>
    <tr class="active">
      <td><%= invitee.name %></td>
      <td><%= invitee.phone_number %></td>
      <td><%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, "delete_invitee?delete_invitee="+invitee.id.to_s, {class: 'btn btn-danger', type: 'button'} %></td>
    </tr>
    <% end %>

<!--<form action="/admin/add_invitee?poll_id=<%#= @poll.id.to_s %>" method="get">-->

      <tr class="active">
          <td>
            <%= text_field_tag :name, nil, {class: "form-control", id: "name"}%>
            <label style="font-size:17px;color:grey">Name of Invitee</label>
          </td>
          <td>
            <%= text_field_tag :phone_number, nil, {class: "form-control", id: "phone_number"} %>
            <label style="font-size:17px;color:grey">Ex. Format: +15635551234</label>
          </td>
          <td><%= button_tag "<span class='glyphicon glyphicon-plus'></span>".html_safe, {:class => 'btn btn-primary form-control', onclick: "invite()", type: "button"} %></td>
        </tr>
        <%#flash[:poll_id] = @poll.id %>
<!--    </form>-->

</table>

<div>
  <%#flash[:poll_invite] = @poll.id %>

  <%=  button_tag "Send Invites", {class: 'btn btn-secondary send_invites_button', onclick: "sendInvites()" ,type: 'button'} %>

</div>

</body>


<% content_for :invite_submission_javascript do %>
  <%= javascript_include_tag "InviteSubmission.js" %>
<% end %>