config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    root to: "devise/sessions#new"

  end

  get 'admin/homepage', as: :admin_root
  get 'admin/start' => 'admin#start'
  get 'admin/end' => 'admin#end'
  get 'admin/delete' => 'admin#delete'
  get 'admin/new' => 'admin#new'
  get 'admin/edit' => 'admin#edit'
  get 'admin/invite' => 'admin#invite'
  get 'admin/delete_invitee' => 'admin#delete_invitee'
  post 'admin/add_invitee' => 'admin#add_invitee'
  post 'admin/send_invites' => 'admin#send_invites'
  get 'admin/log_out' => 'admin#log_out'

  get 'poll/new' => 'poll#new'
  get 'poll/edit' => 'poll#edit'
  post 'poll/edit_time_slots' => 'poll#edit_time_slots'
  post 'poll/update' => 'poll#update'
  post 'poll/choose_time_slots' => 'poll#choose_time_slots'
  post 'poll/create' => 'poll#create'
  get 'poll/vote' => "poll#vote"
  post 'poll/cast_vote' => "poll#cast_vote"
  get 'poll/success' => "poll#success"
  get 'poll/unauthorized' => "poll#unauthorized"

  get 'results/get_results' => 'results#get_results'

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def get_results

    @poll = Poll.find(params[:poll_id])
    @timeslots = Timeslot.where("poll_id = '#{@poll.id}'")
    @title = @poll.poll_name

    @hash_arr = []
    @timeslots.each do |timeslot|
      puts timeslot

      @reservers = Reserver.where("timeslot_id = '#{timeslot.id}'")

      slot = {}

      raw_datetime_start = timeslot.start_time.delete(",").split(" ")
      
      year_start = raw_datetime_start[3].to_i
      month_start = raw_datetime_start[2].downcase
      day_month_start = raw_datetime_start[1].to_i

      atomic_start = raw_datetime_start[4].split(":")
      hours_start = atomic_start[0].to_i
      minutes_start = atomic_start[1].to_i
      seconds_start = 0

      t_start = Time.utc(year_start,month_start,day_month_start,hours_start,minutes_start,seconds_start)
      slot[:start] = t_start.localtime.strftime("%Y-%m-%d %l:%M:%S %p")

      raw_datetime_end = timeslot.end_time.delete(",").split(" ")

      year_end = raw_datetime_end[3].to_i
      month_end = raw_datetime_end[2].downcase
      day_month_end = raw_datetime_end[1].to_i

      atomic_end = raw_datetime_end[4].split(":")
      hours_end = atomic_end[0].to_i
      minutes_end = atomic_end[1].to_i
      seconds_end = 0
      t_end = Time.utc(year_end,month_end,day_month_end,hours_end,minutes_end,seconds_end)
      slot[:end] = t_end.localtime.strftime("%Y-%m-%d %l:%M:%S %p")

      slot[:available] = timeslot.available
      slot[:num_votes] = timeslot.num_votes

      reserver_string = ""
      @reservers.each do |reserver|
        reserver_string += reserver.name + ", "
      end
      reserver_string = reserver_string[0...-2]
      if reserver_string == ""
        reserver_string = "No Reservers"
      end
      slot[:reservers] = reserver_string
      @hash_arr.push(slot)
    end

    puts(@hash_arr)

  end
end

app/views/results/get_results.html.erb
<head>
  <div class="menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Current Polls', admin_root_path %>
        <!--        <a href="homepage">Current Polls</a>-->
      </div>
      <div>
        <ul class="nav navbar-nav navbar-right">
          <li><a>Logged in as: <%= @current_user %></a></li>

          <li> <%= link_to 'Log Out', destroy_admin_session_path, method: :delete %> </li>
          <!--          <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Log Out </a></li>-->
        </ul>
      </div>
    </div>
  </div>
</head>

<h1 style="text-align: center; position: relative; top: 80px; margin:auto">Poll Results for Poll: <%= @title %></h1>

<table id="poll_table" style="width:90%;margin:0 auto;font-size:20px;position:relative;top:95px" class="table table-striped table-sm">
  <thead>
  <tr>
    <th scope="col">Reserver ID</th>
    <th scope="col">Start Time</th>
    <th scope="col">End Time</th>
    <th scope="col">Number of Votes</th>
    <th scope="col">Available</th>
  </tr>
  <tbody>
  <tr>
  </tbody>

  <% @hash_arr.each do |timeslot| %>
    <%if timeslot[:available] == false %>
        <td><%=timeslot[:reservers]%></td>
        <td><%=timeslot[:start]%></td>
        <td><%=timeslot[:end]%></td>
        <td><%=timeslot[:num_votes]%></td>
        <td><%=timeslot[:available]%></td>
        </tr>
        <% end %>
    <%end %>
  <% @hash_arr.each do |timeslot| %>
    <%if timeslot[:available] == true %>
        <td><%=timeslot[:reservers]%></td>
        <td><%=timeslot[:start]%></td>
        <td><%=timeslot[:end]%></td>
        <td><%=timeslot[:num_votes]%></td>
        <td><%=timeslot[:available]%></td>
        </tr>
    <% end %>
  <% end %>
  </thead>
</table>